// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts"
// @generated from file rpc/sample/v1/health.proto (package rpc.sample.v1, syntax proto3)
/* eslint-disable */

import { HealthService } from "./health_pb";

/**
 * サービスの動作状況を確認
 *
 * @generated from rpc rpc.sample.v1.HealthService.Check
 */
export const check = HealthService.method.check;
